# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Archive', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa-brands fa-github', link: 'https://github.com/rubenhoenle'}
#- {icon: 'fa-brands fa-mastodon', link: 'https://mastodon.social/@rubenhoenle@techhub.social'}
- {icon: 'fa fa-envelope', link: 'mailto:rubenhoenle.e27vw@aleeas.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'fa fa-square-rss', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share this post with your friends!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
