name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PAGES_CNAME: hoenle.xyz

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@V27

      - name: Check code format
        run: nix flake check

      - name: Build
        run: nix build .#html

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref_name == 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'          
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: ./result
          cname: ${{ env.PAGES_CNAME }}

